services:
  server:
    build: ./server
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_NAME=${EMAIL_NAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_SECRET_API=${CLOUDINARY_SECRET_API}
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_TINY_MCE_API_KEY=${NEXT_PUBLIC_TINY_MCE_API_KEY}
        - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        - NEXT_PUBLIC_RECAPTCHA_SECRET_KEY=${NEXT_PUBLIC_RECAPTCHA_SECRET_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
